# device id is unique to each device and is used on the cloud
device_id: "uid8933674632"

access_point_ssid: "127.80.034"
access_point_password: "example_password"
ip_edge_device: "127.90.034"
port_edge_device: "8080"

protocol_version: "v1.0.0"

# Seconds between each message
transmission_rate: 60

# sensors contains a list of sensors that are connected to the device.
# The order of the readings in a message will be the top down order of 
# all of the "values" in this file.
sensors:
  - 0:
    # The path is the sensor path, the end device can read 
    # and write to it in order to communicate with the sensor
    name: "SpecNo2Sensor"
    path: "/dev/ttyUSB0"
    # values contain all the different attributes a sensor captures.
    # The value of each attribute is the number of bytes the device 
    # will use to send the reading. 
    values:
      - temp: 4
      - hum: 0
      - no2: 2
  - 1:
    name: "SpecCoSensor"
    path: "/dev/ttyUSB0"
    values: 
      - temp: 0
      - hum: 4
      - co: 2