# device id is unique to each device and is used on the cloud
device_id: "uid8933674632"

# edge_device_addr is the address the device will use to connect with over wifi
edge_device_addr: "fds34432423"
# edge_device_pass is the password the device will use to connect with over wifi
edge_device_pass: "password"

# sensors contains a list of sensors that are connected to the device.
# The order of the readings in a message will be the top down order of 
# all of the "values" in this file.
sensors:
  - SPEC_DGS_NO2:
    # The path is the sensor path, the end device can read 
    # and write to it in order to communicate with the sensor
    - path: "/dev/ttyUSB0"
    # values contain all the different attributes a sensor captures.
    # The value of each attribute is the number of bytes the device 
    # will use to send the reading. 
    - values:
      - temp: 4
      - hum: 0
      - no2: 2
  - SPEC_DGS_CO:
    - path: "/dev/ttyUSB1"
    - values: 
      - temp: 0
      - hum: 4
      - co: 2

